export const RouteIndex = '/'
export const RouteSignin = '/signin'
export const RouteSignup = '/signup'
export const RouteLogout = '/signout'
export const RouteProfile = '/profile'
export const BlogLayout = '/bloglayout'